Repository OpenKore/openkore, pull requests merged in 2018-06, with the labels that each got.

#2045 cRO Packet Update
  tables/cRO/recvpackets.txt
  tables/cRO/shuffle.txt
  tables/cRO/sync.txt
Labels: server: cRO

#1975 New servertype for pServer
  src/Network/Receive/kRO/Distfiles
  src/Network/Receive/kRO/RagexeRE_2017_02_01a.pm
  src/Network/Receive/kRO/RagexeRE_2017_02_08b.pm
  src/Network/Receive/kRO/RagexeRE_2017_04_12a.pm
  src/Network/Send/kRO/Distfiles
  src/Network/Send/kRO/RagexeRE_2015_09_16.pm
  src/Network/Send/kRO/RagexeRE_2017_02_01a.pm
  src/Network/Send/kRO/RagexeRE_2017_02_08b.pm
  src/Network/Send/kRO/RagexeRE_2017_04_12a.pm
  tables/kRO/RagexeRE_2017_02_01a/recvpackets.txt
  tables/kRO/RagexeRE_2017_02_08b/recvpackets.txt
Labels: server: Private

#2068 [System] Elemental Spirit
  src/Actor.pm
  src/Actor/Elemental.pm
  src/ActorList.pm
  src/Commands.pm
  src/Globals.pm
  src/Misc.pm
  src/Network/Receive.pm
  src/functions.pl
Labels: enhancement, needs code review, priority: medium

#2083 [Feature] Command cook update
  src/Commands.pm
  src/Globals.pm
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
  src/Network/Send.pm
  src/Network/Send/ServerType0.pm
  src/Network/Send/kRO/Sakexe_0.pm
  src/Network/Send/kRO/Sakexe_2005_10_10a.pm
  src/functions.pl
Labels: needs code review, new feature, priority: high

#2103 [raiseSkill] Fix typo in portuguese translation
  plugins/raiseSkill/po/pt.mo
  plugins/raiseSkill/po/pt.po
Labels: plugin, translation
