Repository OpenKore/openkore, pull requests merged in 2019-04, with the labels that each got.

#2722 Review all Carp::Assert::assert calls
  src/Actor.pm
  src/ActorList.pm
  src/Base/Ragnarok/SessionStore.pm
  src/InventoryList.pm
  src/Misc.pm
  src/Network/MessageTokenizer.pm
  src/Network/Receive.pm
  src/Settings.pm
  src/Skill.pm
  src/Task/Route.pm
  src/Task/WithSubtask.pm
  src/TaskManager.pm
  src/Utils/CallbackList.pm
  src/Utils/ObjectList.pm
Labels: code cleaning, enhancement

#2729 Remove blessed requirement
  src/Utils/Assert.pm
Labels: priority: urgent

#2746 Packet Update - IRO Re:Start & Renewal
  tables/iRO/Renewal/recvpackets.txt
  tables/iRO/Renewal/shuffle.txt
  tables/iRO/Renewal/sync.txt
  tables/iRO/Restart/recvpackets.txt
  tables/iRO/Restart/shuffle.txt
  tables/iRO/Restart/sync.txt
  tables/servers.txt
Labels: server: iRO, server: iRO Re:start
