Repository OpenKore/openkore, pull requests merged in 2019-10, with the labels that each got.

#2793 Add self_interruptible automacro parameter
  plugins/eventMacro/eventMacro.pl
  plugins/eventMacro/eventMacro/Automacro.pm
  plugins/eventMacro/eventMacro/Core.pm
  plugins/eventMacro/eventMacro/Data.pm
  plugins/eventMacro/eventMacro/Runner.pm
  plugins/eventMacro/test/RunnerParseCommandTest.pm
  plugins/eventMacro/test/RunnerStatementTest.pm
Labels: documentation

#2916 IRO: RE Update !
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/iRO.pm
  src/Network/Receive/iRO/Renewal.pm
  src/functions.pl
  tables/iRO/Renewal/recvpackets.txt
  tables/iRO/Renewal/shuffle.txt
  tables/iRO/Renewal/sync.txt
  tables/iRO/official/items.txt
  tables/iRO/official/itemsdescriptions.txt
  tables/iRO/official/quests.txt
  tables/servers.txt
Labels: server: iRO

#2941 Change avoid gm and avoid list
  control/avoid.txt
  control/config.txt
  src/Misc.pm
Labels: documentation, feature request

#2953 Cmd plugin fix
  src/Commands.pm
Labels: bug, code cleaning
