Repository OpenKore/openkore, pull requests merged in 2021-04, with the labels that each got.

#3387 update servertypes.txt for cRO
  src/Poseidon/servertypes.txt
Labels: server: cRO

#3390 [Hotfix] Fix kRO packets
  src/Network/Receive.pm
  src/Network/Receive/RMS.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
  src/Network/Send.pm
  src/Network/Send/kRO/RagexeRE_2008_09_10a.pm
  src/Network/Send/kRO/RagexeRE_2010_04_20a.pm
  src/Network/Send/kRO/RagexeRE_2010_11_24a.pm
  src/Network/Send/kRO/RagexeRE_2011_10_05a.pm
  src/Network/Send/kRO/RagexeRE_2013_05_22.pm
  src/Network/Send/kRO/RagexeRE_2014_09_17c.pm
  src/Network/Send/kRO/RagexeRE_2014_10_22b.pm
  src/Network/Send/kRO/RagexeRE_2015_11_18a.pm
  src/Network/Send/kRO/RagexeRE_2015_12_02.pm
  src/Network/Send/kRO/RagexeRE_2017_05_17a.pm
  src/Network/Send/kRO/RagexeRE_2017_07_26c.pm
  src/Network/Send/kRO/RagexeRE_2017_10_02c.pm
  src/Network/Send/kRO/RagexeRE_2017_10_18a.pm
  src/Network/Send/kRO/RagexeRE_2018_04_04b.pm
  src/Network/Send/kRO/RagexeRE_2020_03_04a.pm
  src/Network/Send/kRO/Sakexe_2005_04_25a.pm
  src/Network/Send/kRO/Sakexe_2005_06_08a.pm
  src/Network/Send/kRO/Sakexe_2008_09_10a.pm
Labels: bug, code cleaning

#3371 [Fix] fix buy when npc is ParaMarket
  src/AI/CoreLogic.pm
  src/Network/Receive/tRO.pm
  src/Network/Send/tRO.pm
Labels: bug, server: tRO

#3399 [Misc] add ignoreAntiCheatWarning to config
  control/config.txt
  src/Network/Receive.pm
  src/Network/Receive/pRO.pm
  src/Network/Receive/tRO.pm
Labels: documentation

#3401 bug fix for mon_control
  src/Network/Receive.pm
Labels: bug, code cleaning, server: cRO, server: rRO

#3289 Fix buyer shop in 4 byte itemID
  src/Network/Send.pm
  src/Network/Send/bRO.pm
  src/Network/Send/cRO.pm
  src/Network/Send/iRO/Renewal.pm
  src/Network/Send/iRO/Transcendence.pm
  src/Network/Send/idRO/Renewal.pm
  src/Network/Send/kRO/RagexeRE_2020_03_04a.pm
  src/Network/Send/tRO.pm
Labels: hacktoberfest-accepted

#3406 [Network] Add support to mac encryption in packet game_login
  control/config.txt
  src/Network/Send.pm
Labels: documentation, new feature

#3410 adding a new package 0AFB
  src/Network/Receive/ServerType0.pm
Labels: new feature, server: rRO

#3413 [Network / Send] Cleaning Packets part 2 (OpenKore#3382)
  src/Network/Send/iRO/Renewal.pm
Labels: code cleaning

#3411 fix pauseCharLogin
  control/config.txt
  control/timeouts.txt
  src/Network/Receive.pm
Labels: code cleaning, documentation

#3412 code cleanup
  control/config.txt
  src/Network/DirectConnection.pm
  src/functions.pl
Labels: code cleaning, documentation

#3414 [misc] move ignoreAntiCheatWarning to servers.txt
  control/config.txt
  src/Network/Receive.pm
  tables/servers.txt
Labels: code cleaning, documentation

#3418 added a new callHook "friend_request"
  plugins/alertSound/README.txt
  plugins/alertSound/alertSound.pl
  src/Network/Receive.pm
Labels: feature request
