Repository OpenKore/openkore, pull requests merged in 2021-03, with the labels that each got.

#3367 [alertSound] fixed eventList item
  plugins/alertSound/README.txt
  plugins/alertSound/alertSound.pl
Labels: bug

#3374 Merge meetingPosition for char and slaves
  src/AI/Attack.pm
  src/AI/Slave.pm
  src/Misc.pm
Labels: code cleaning

#3380 [Feature] (re)load files using path
  src/Settings.pm
  src/functions.pl
Labels: bug, documentation
