Repository OpenKore/openkore, pull requests merged in 2021-05, with the labels that each got.

#3416 remove followCheckLOS
  src/AI/CoreLogic.pm
  tables/bRO/control-br/config.txt
  tables/twRO/chinese/control/config.txt
Labels: code cleaning

#3423 replaced OTT with OTP
  src/Network/Receive.pm
  src/Network/Send.pm
  tables/servers.txt
Labels: code cleaning, documentation

#3424 merge removeActorWithDistance and clientSight
  control/config.txt
  plugins/needs-review/autokach/trunk/control/config.txt
  src/Misc.pm
  src/Network/Receive.pm
  tables/bRO/control-br/config.txt
  tables/twRO/chinese/control/config.txt
Labels: code cleaning, documentation

#3431 [Network] buying store packet update
  src/Network/Receive.pm
  src/Network/Receive/pRO.pm
  src/Network/Send/pRO.pm
Labels: new feature

#3434 fixed autosell and autostorage distance
  control/config.txt
  src/AI/CoreLogic.pm
  tables/servers.txt
Labels: code cleaning, documentation
