Repository OpenKore/openkore, pull requests merged in 2021-02, with the labels that each got.

#3343 fixed cash shop
  .github/workflows/test.yml
  src/Commands.pm
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
  src/Network/Send.pm
Labels: bug, code cleaning, documentation

#3345 fixed attendance_ui function
  control/config.txt
  src/Network/Receive.pm
Labels: code cleaning, documentation, new feature

#3353 fix item_appeared
  src/Network/Receive/cRO.pm
Labels: bug, server: cRO

#3282 Add 20200304 Support !
  src/Network/Receive.pm
  src/Network/Receive/kRO/RagexeRE_2020_03_04a.pm
  src/Network/Receive/kRO/Sakexe_0.pm
  src/Network/Send/kRO/RagexeRE_2020_03_04a.pm
Labels: feature request, help wanted, server: Private
