Repository OpenKore/openkore, pull requests merged in 2021-07, with the labels that each got.

#3452 added new serverType
  src/Network/Receive/kRO/RagexeRE_2020_04_01b.pm
  src/Network/Send/kRO/RagexeRE_2020_04_01b.pm
  tables/kRO/RagexeRE_2020_04_01b/recvpackets.txt
Labels: server: kRO

#3450 party_bug_autovivification
  src/AI/CoreLogic.pm
  src/Actor.pm
  src/Misc.pm
Labels: bug

#3453 vRO support
  README.md
  plugins/!deps/HTTP/Config.pm
  plugins/!deps/HTTP/Date.pm
  plugins/!deps/HTTP/Headers.pm
  plugins/!deps/HTTP/Message.pm
  plugins/!deps/HTTP/Request.pm
  plugins/!deps/HTTP/Request/Common.pm
  plugins/!deps/HTTP/Response.pm
  plugins/!deps/HTTP/Status.pm
  plugins/!deps/LWP.pm
  plugins/!deps/LWP/MemberMixin.pm
  plugins/!deps/LWP/Protocol.pm
  plugins/!deps/LWP/Protocol/http.pm
  plugins/!deps/LWP/Simple.pm
  plugins/!deps/LWP/UserAgent.pm
  plugins/!deps/Net/HTTP.pm
  plugins/!deps/Net/HTTP/Methods.pm
  plugins/!deps/Time/Local.pm
  plugins/!deps/URI.pm
  plugins/!deps/URI/Escape.pm
  plugins/!deps/URI/_generic.pm
  plugins/!deps/URI/_query.pm
  plugins/!deps/URI/_server.pm
  plugins/!deps/URI/http.pm
  plugins/vRO_auth/vRO_auth.pl
  src/Network/Receive.pm
  src/Network/Receive/vRO.pm
  src/Network/Send/vRO.pm
  tables/cities.txt
  tables/servers.txt
  tables/vRO/achievement_list.txt
  tables/vRO/attendance_rewards.txt
  tables/vRO/items.txt
  tables/vRO/itemsdescriptions.txt
  tables/vRO/itemslotcounttable.txt
  tables/vRO/itemslots.txt
  tables/vRO/maps.txt
  tables/vRO/msgstringtable.txt
  tables/vRO/pets.txt
  tables/vRO/quests.txt
  tables/vRO/recvpackets.txt
  tables/vRO/resnametable.txt
  tables/vRO/skillnametable.txt
  tables/vRO/skillsdescriptions.txt
  tables/vRO/skillssp.txt
  tables/vRO/statusnametable.txt
Labels: feature request

#3454 TwRO support
  src/Network/Receive.pm
  src/Network/Receive/twRO.pm
  src/Network/Send/twRO.pm
  tables/servers.txt
  tables/twRO/STATUS_id_handle.txt
  tables/twRO/achievement_list.txt
  tables/twRO/attendance_rewards.txt
  tables/twRO/hateffect_id_handle.txt
  tables/twRO/hateffect_name.txt
  tables/twRO/item_options.txt
  tables/twRO/items.txt
  tables/twRO/itemsdescriptions.txt
  tables/twRO/itemslotcounttable.txt
  tables/twRO/itemslots.txt
  tables/twRO/maps.txt
  tables/twRO/msgstringtable.txt
  tables/twRO/quests.txt
  tables/twRO/recvpackets.txt
  tables/twRO/recvpackets_sakray.txt
  tables/twRO/resnametable.txt
  tables/twRO/skillnametable.txt
  tables/twRO/skillsdescriptions.txt
  tables/twRO/skillssp.txt
  tables/twRO/statusnametable.txt
  tables/twRO/sync.txt
  tables/twRO/title_name.txt
Labels: feature request, server: twRO

#3456 Updated the busParty plugin
  plugins/needs-review/busParty/README.md
  plugins/needs-review/busParty/busParty.pl
  plugins/needs-review/busParty/trunk/busParty.pl
  plugins/needs-review/busParty/trunk/doc/README.txt
  src/Commands.pm
Labels: plugin

#3476 [Translation] update portuguese files
  src/po/pt.mo
  src/po/pt.po
Labels: translation

#3478 [bRO] translate table files
  tables/bRO/elements.txt
  tables/bRO/itemtypes.txt
Labels: translation

#3484 code cleanup
  src/Commands.pm
  src/Network/Receive.pm
Labels: code cleaning

#3483 fixed partyAuto
  src/AI/CoreLogic.pm
Labels: bug

#3473 Translate interface and skillname into vietnamese
  src/po/update.sh
  src/po/vi.mo
  src/po/vi.po
  tables/vRO/directions.txt
  tables/vRO/elements.txt
  tables/vRO/equiptypes.txt
  tables/vRO/haircolors.txt
  tables/vRO/itemtypes.txt
  tables/vRO/sex.txt
Labels: translation

#3487 Fix not closed file handler
  src/Utils/TextReader.pm
Labels: code cleaning

#3489 [fix] update vender_found unpack string
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
Labels: bug

#3491 rodex fixes
  src/Commands.pm
  src/Network/Receive.pm
Labels: bug, server: twRO
