Repository OpenKore/openkore, pull requests merged in 2021-11, with the labels that each got.

#3535 remove pRO files
  README.md
  src/Network/Receive/pRO.pm
  src/Network/Send/pRO.pm
  src/test/NetworkTest.pm
  tables/pRO/STATUS_id_handle.txt
  tables/pRO/attendance_rewards.txt
  tables/pRO/hateffect_id_handle.txt
  tables/pRO/hateffect_name.txt
  tables/pRO/items.txt
  tables/pRO/itemsdescriptions.txt
  tables/pRO/itemslotcounttable.txt
  tables/pRO/itemslots.txt
  tables/pRO/maps.txt
  tables/pRO/msgstringtable.txt
  tables/pRO/portals.txt
  tables/pRO/quests.txt
  tables/pRO/recvpackets.txt
  tables/pRO/resnametable.txt
  tables/pRO/skillnametable.txt
  tables/pRO/skillsdescriptions.txt
  tables/pRO/skillssp.txt
  tables/pRO/statusnametable.txt
  tables/pRO/sync.txt
  tables/servers.txt
Labels: code cleaning, server: pRO

#3536 update makedist.sh
  Distfiles
  makedist.sh
  src/Actor/Slave/Distfiles
  src/Distfiles
  src/Network/Receive/Distfiles
  src/Network/Receive/iRO/Distfiles
  src/Network/Receive/idRO/Distfiles
  src/Network/Receive/kRO/Distfiles
  src/Network/Send/Distfiles
  src/Network/Send/iRO/Distfiles
  src/Network/Send/idRO/Distfiles
  src/Network/Send/kRO/Distfiles
  src/auto/XSTools/darwin/include/Distfiles
  src/po/Distfiles
  src/scons-local-3.1.2/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Node/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Platform/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Scanner/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Script/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Tool/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Tool/MSCommon/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Tool/clangCommon/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Tool/docbook/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Tool/packaging/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Variables/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/compat/Distfiles
  src/test/Distfiles
  src/test/Utils/Distfiles
  src/test/data/Distfiles
  src/test/data/child/Distfiles
Labels: code cleaning

#3539 readme update
  README.md
Labels: server: twRO, server: vRO

#3537 update GitHub Actions
  .github/workflows/build_XSTools.yml
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Node/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Platform/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Scanner/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Script/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Tool/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/Variables/Distfiles
  src/scons-local-3.1.2/scons-local-3.1.2/SCons/compat/Distfiles
Labels: feature request, code cleaning
