Repository OpenKore/openkore, pull requests merged in 2022-09, with the labels that each got.

#3613 fix: update processtake logic
  control/config.txt
  plugins/needs-review/autokach/trunk/control/config.txt
  src/AI/CoreLogic.pm
  tables/bRO/control-br/config.txt
  tables/twRO/chinese/control/config.txt
Labels: documentation, code cleaning

#3612 fix: update wx font dialog
  control/sys.txt
  src/Interface/Wx.pm
  src/Interface/Wx/Console.pm
Labels: documentation, interface: Wx

#3615 feat: implement guild storage
  control/config.txt
  src/Commands.pm
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
  src/Network/Send.pm
  src/Network/Send/ServerType0.pm
  src/Network/Send/kRO/Sakexe_0.pm
  tables/packetdescriptions.txt
Labels: documentation, new feature

#3622 added defaul value for attackRouteMaxPathDistance
  src/Misc.pm
Labels: bug, documentation

#3620 Fix attackAuto_inLockOnly
  control/config.txt
  src/AI/CoreLogic.pm
Labels: bug, documentation

#3631 fix runFromTarget_maxPathDistance
  control/config.txt
  src/Misc.pm
Labels: bug

#3630 add attackChangeTarget check
  src/AI/Attack.pm
Labels: new feature

#3633 Update slave attack AI
  control/config.txt
  control/timeouts.txt
  src/AI.pm
  src/AI/Attack.pm
  src/AI/CoreLogic.pm
  src/AI/Slave.pm
  src/AI/SlaveAttack.pm
  src/AI/SlaveManager.pm
  src/Misc.pm
Labels: documentation, needs to be tested, new feature

#3641 Recompile portals after new record
  control/config.txt
  src/AI/CoreLogic.pm
Labels: enhancement

#3639 fixed party user
  src/Network/Receive.pm
Labels: bug

#3642 Remove unused follow code from Attack.pm
  src/AI/Attack.pm
Labels: code cleaning

#3643 Clean route_tryToGuessMissingPortalByDistance
  src/Task/MapRoute.pm
Labels: enhancement
