Repository OpenKore/openkore, pull requests merged in 2022-08, with the labels that each got.

#3594 feat: add 0x0b1a skill_cast packet
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
Labels: new feature

#3595 feat: add starplace packet
  src/Commands.pm
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
Labels: documentation, new feature

#3603 updating ubuntu versions
  .github/workflows/build_XSTools.yml
Labels: code cleaning

#3610 fix: update xpmmake
  XSTools.dll
  src/auto/XSTools/misc/fastutils.xs
Labels: new feature

#3609 fix: remove rms network files
  src/Network/Receive.pm
  src/Network/Receive/Distfiles
  src/Network/Receive/RMS.pm
  src/Network/Send/Distfiles
  src/Network/Send/RMS.pm
Labels: code cleaning

#381 Changes to plugin loading functions
  src/Commands.pm
  src/Plugins.pm
Labels: documentation, new feature

#3493 [fix] unable to talk to npc and can't drop target
  control/config.txt
  control/timeouts.txt
  src/AI.pm
  src/AI/Attack.pm
  src/AI/CoreLogic.pm
  src/AI/Slave.pm
  src/Misc.pm
  src/Network/Receive.pm
  src/Task/Route.pm
Labels: bug

#3597 feat: add 0x0b77 npc_store_info packet
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
Labels: new feature

#3605 feat: update tk interface
  src/Interface/Tk.pm
Labels: enhancement

#3614 feat: implement macro detector
  src/Commands.pm
  src/Globals.pm
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
  src/Network/Send.pm
  src/Network/Send/ServerType0.pm
  src/Network/Send/kRO/Sakexe_0.pm
  tables/packetdescriptions.txt
Labels: documentation, new feature
