Repository OpenKore/openkore, pull requests merged in 2023-02, with the labels that each got.

#3696 code cleanup
  control/config.txt
  src/AI/CoreLogic.pm
  src/AI/Distfiles
  src/Network/Receive.pm
Labels: documentation, code cleaning

#3710 fix: move sold item message to network receive
  src/Commands.pm
  src/Network/Receive.pm
Labels: bug

#3706 hotfix: update callhook double quote (#3692)
  src/Network/PacketParser.pm
Labels: bug, discussion, priority: urgent

#3727 fix: update 0x09de unpack string
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
Labels: bug
