Repository OpenKore/openkore, pull requests merged in 2023-03, with the labels that each got.

#3716 feat: rodex use current mailbox opentype
  src/Commands.pm
  src/Globals.pm
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Send.pm
Labels: enhancement, documentation, needs to be tested, new feature

#3699 fix: correct reuse of char in character select screen
  src/Network/Receive.pm
Labels: code cleaning

#3700 fix: add support to old items type in item list
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
  tables/servers.txt
Labels: documentation, new feature

#3734 rodex code cleanup
  src/Commands.pm
  src/Network/Receive.pm
Labels: code cleaning
