Repository OpenKore/openkore, pull requests merged in 2023-04, with the labels that each got.

#3739 feat: move wx alias menu interface to its own menu bar
  src/Interface/Wx.pm
Labels: interface: Wx

#3744 new log added: playerLog
  control/config.txt
  src/Misc.pm
  src/Network/Receive.pm
  src/Settings.pm
Labels: feature request, documentation

#3712 feat: implement monstercountdist in checkselfcondition
  control/config.txt
  src/Misc.pm
Labels: enhancement, documentation, new feature

#3621 added aRO support
  src/Network/Receive.pm
  src/Network/Receive/aRO.pm
  src/Network/Send/aRO.pm
  tables/aRO/attendance_rewards.txt
  tables/aRO/item_options.txt
  tables/aRO/items.txt
  tables/aRO/itemsdescriptions.txt
  tables/aRO/itemslotcounttable.txt
  tables/aRO/itemslots.txt
  tables/aRO/maps.txt
  tables/aRO/msgstringtable.txt
  tables/aRO/quests.txt
  tables/aRO/recvpackets.txt
  tables/aRO/resnametable.txt
  tables/aRO/skillnametable.txt
  tables/aRO/skillsdescriptions.txt
  tables/aRO/skillssp.txt
  tables/aRO/statusnametable.txt
  tables/servers.txt
Labels: new feature
