Repository OpenKore/openkore, pull requests merged in 2024-12, with the labels that each got.

#3896 add memorial_dungeon_command
  src/Commands.pm
  src/Network/Send.pm
  src/Network/Send/ServerType0.pm
  src/Network/Send/kRO/Sakexe_0.pm
Labels: feature request, documentation

#3897 remove verbose command
  src/Commands.pm
Labels: documentation, code cleaning

#3900 Added support for 02F7 package (guild_name)
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
Labels: new feature

#3901 Moving MediaServer from the main code to the archive
  plugins/needs-review/MediaServer/How to run the media server.txt
  plugins/needs-review/MediaServer/MediaServer.pm
  plugins/needs-review/MediaServer/mediaserver.pl
  src/MediaServer/Distfiles
Labels: code cleaning

#3789 add attackAuto_notWhile for slaves
  control/config.txt
  src/AI/Slave.pm
Labels: documentation, new feature

#3902 feat: add support to AP
  control/config.txt
  src/Actor/You.pm
  src/Commands.pm
  src/Misc.pm
Labels: documentation, new feature

#3910 suppress the output of the sprite_change message
  src/Network/Receive.pm
Labels: code cleaning

#3916 Minimum package support 0A15 (PACKET_ZC_GOLDPCCAFE_POINT)
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
Labels: new feature

#3918 Fix skill failed packet
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
Labels: bug

#3914 Fix slave skills
  src/AI.pm
  src/AI/CoreLogic.pm
  src/AI/Slave.pm
  src/AI/SlaveManager.pm
  src/Actor/You.pm
  src/Commands.pm
  src/Misc.pm
  src/Network/Receive.pm
Labels: bug, new feature

#3923 fix: correct calcposition call at party logic
  src/AI/CoreLogic.pm
  src/Network/XKore2.pm
Labels: bug

#3676 feat: Pathfinding v3 + Attack rework
  NetRedirect.dll
  XSTools.dll
  control/config.txt
  control/timeouts.txt
  plugins/NewAStarAvoid/NewAStarAvoid.pl
  src/AI.pm
  src/AI/Attack.pm
  src/AI/CoreLogic.pm
  src/AI/Slave.pm
  src/AI/SlaveAttack.pm
  src/AI/SlaveManager.pm
  src/Actor.pm
  src/Actor/You.pm
  src/Commands.pm
  src/Field.pm
  src/Interface/Wx.pm
  src/Interface/Wx/MapViewer.pm
  src/Misc.pm
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
  src/Task/MapRoute.pm
  src/Task/Move.pm
  src/Task/Route.pm
  src/Utils.pm
  src/Utils/PathFinding.pm
  src/auto/XSTools/PathFinding/PathFinding.xs
  src/auto/XSTools/PathFinding/algorithm.cpp
  src/auto/XSTools/PathFinding/algorithm.h
Labels: enhancement, priority: medium, needs to be tested, needs code review
