Repository OpenKore/openkore, pull requests merged in 2025-01, with the labels that each got.

#3933 Fixed a bug in GitHub Actions
  .github/workflows/build_XSTools.yml
Labels: priority: high, code cleaning

#3927 Added loginPinCode support in XKore3 mode
  src/Network/XKoreProxy.pm
Labels: new feature

#3938 Fix eventMacro quests
  plugins/eventMacro/eventMacro/Condition/QuestActive.pm
  plugins/eventMacro/eventMacro/Condition/QuestHuntCompleted.pm
  plugins/eventMacro/eventMacro/Condition/QuestHuntOngoing.pm
  plugins/eventMacro/eventMacro/Condition/QuestInactive.pm
  plugins/eventMacro/eventMacro/Condition/QuestOnTime.pm
  plugins/eventMacro/eventMacro/Condition/QuestTimeOverdue.pm
  src/Network/Receive.pm
Labels: bug, plugin

#3936 Fix eventmacro inventory
  plugins/eventMacro/eventMacro/Condition/Base/InInventory.pm
  plugins/eventMacro/eventMacro/Condition/InventoryCurrentSize.pm
  plugins/eventMacro/eventMacro/Condition/IsEquippedID.pm
  plugins/eventMacro/eventMacro/Condition/IsNotEquippedID.pm
  src/InventoryList/Inventory.pm
Labels: bug, plugin

#3937 Fix eventmacro lvl hp sp conditions
  plugins/eventMacro/eventMacro/Condition/BaseLevel.pm
  plugins/eventMacro/eventMacro/Condition/CurrentHP.pm
  plugins/eventMacro/eventMacro/Condition/CurrentSP.pm
  plugins/eventMacro/eventMacro/Condition/JobLevel.pm
  plugins/eventMacro/eventMacro/Condition/MaxHP.pm
  plugins/eventMacro/eventMacro/Condition/MaxSP.pm
Labels: bug, plugin

#3928 Removed melee-ranged unnecessary message and check
  src/AI/Attack.pm
  src/AI/SlaveAttack.pm
Labels: enhancement, priority: low, code cleaning

#3952 Minimum package support 0A16 and 0A17
  src/Commands.pm
  src/Network/Receive.pm
  src/Network/Receive/ServerType0.pm
  src/Network/Receive/kRO/Sakexe_0.pm
  src/Network/Send.pm
  src/Network/Send/ServerType0.pm
  src/Network/Send/kRO/Sakexe_0.pm
Labels: feature request, documentation

#3958 Fix attackSkillSlot maxattempts
  src/AI/Attack.pm
  src/AI/SlaveAttack.pm
Labels: code cleaning

#3957 add Pathfinding to getBestTarget
  src/Misc.pm
Labels: code cleaning

#3953 chore: move skill target time to ai_v temp
  src/AI/Attack.pm
  src/AI/CoreLogic.pm
  src/AI/SlaveAttack.pm
  src/Misc.pm
Labels: code cleaning
